org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=false
MYAPP_UPLOAD_STORE_FILE=triba-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=triba
MYAPP_UPLOAD_STORE_PASSWORD=triba123
MYAPP_UPLOAD_KEY_PASSWORD=triba123
